### ISSUE TITLE
Discuss color

### ISSUE THREAD

**Issue by kamontat** [kamontat/Portfolio#53]
## Helper

- [X] grey (black) - `#333333`
- [X] white - `#FAFAFA`

## Color light theme

- [X] primary - `#60C1E8`
- [X] secondary - `#FFA6C9`
- [X] red (error) - `#FF6666`
- [x] green (pass) - `#96DFA9`

## Color dark theme

- [X] primary - `#4C9AB9`
- [X] secondary - `#FE5BAC`
- [X] red (error) - `#FF0000`
- [X] green (pass) - `#2CBE4E`

## Favorite color

- [X] red light - `#FF3333`
- [X] red dark - `#E60000`
- [X] yellow light - `#FFE97F`
- [X] yellow dark - `#FFD300`

**Comment by kamontat** [comment]
Primary is #60C1E8

**Comment by kamontat** [comment]
Secondary ? `#008080` - https://www.color-hex.com/color/008080
Grey ? `#666666` - https://www.color-hex.com/color/666666

**Comment by kamontat** [comment]
Wait for discussion

**Comment by prangnt** [comment]
#ffe97f - yellow light
#FFD300 - yellow dark

**Comment by prangnt** [comment]
#FFA6C9 - pink light 
#FE5BAC - pink dark

**Comment by prangnt** [comment]
Icon
font - Krala
font-size - 236.65 pt

**Comment by kamontat** [comment]
Closed.
